### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by maddy45** [knassar702/scant3r#1]
i am getting error while running it on ubuntu 16.04 
python scant3r.py --help
  File "scant3r.py", line 86
    print(f"{info} This Proxy Not Supported from ScanT3r")
                                                        ^
SyntaxError: invalid syntax

**Comment by ahmed1231230** [comment]
Use python version 3
`python3 Scant3r.py  - - help`

**Comment by maddy45** [comment]
python3 scant3r.py -u 'http://google.com' --proxy='http://127.0.0.1:8080'
  File "scant3r.py", line 86
    print(f"{info} This Proxy Not Supported from ScanT3r")
                                                        ^
SyntaxError: invalid syntax

still the same tried 
python3 scant3r -u 'http://google.com' --proxy='http://127.0.0.1:8080'

**Comment by maddy45** [comment]
here is the output of setup.py
python setup.py --help
Common commands: (see '--help-commands' for more)

  setup.py build      will build the package underneath 'build/'
  setup.py install    will install the package

Global options:
  --verbose (-v)      run verbosely (default)
  --quiet (-q)        run quietly (turns verbosity off)
  --dry-run (-n)      don't actually do anything
  --help (-h)         show detailed help message
  --no-user-cfg       ignore pydistutils.cfg in your home directory
  --command-packages  list of packages that provide distutils commands

Information display options (just display information, ignore any commands)
  --help-commands     list all available commands
  --name              print package name
  --version (-V)      print package version
  --fullname          print <package name>-<version>
  --author            print the author's name
  --author-email      print the author's email address
  --maintainer        print the maintainer's name
  --maintainer-email  print the maintainer's email address
  --contact           print the maintainer's name if known, else the author's
  --contact-email     print the maintainer's email address if known, else the
                      author's
  --url               print the URL for this package
  --license           print the license of the package
  --licence           alias for --license
  --description       print the package description
  --long-description  print the long package description
  --platforms         print the list of platforms
  --classifiers       print the list of classifiers
  --keywords          print the list of keywords
  --provides          print the list of packages/modules provided
  --requires          print the list of packages/modules required
  --obsoletes         print the list of packages/modules made obsolete

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

**Comment by knassar702** [comment]
Hi sir .. Scant3r Working on this version of python ```3.7.3``` 
Run this command ```$ python3 -V``` for show the version of python
