### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by hellofresh01** [knassar702/scant3r#17]
Whenver i am trying to execute scant3r
i am getting this error

  line 12, in __init__
    self.payloads = XSS(opts['blindxss']).payloads
   line 20, in __init__
    self.blind.append(p.rstrip().format(b64_host=b64_host).replace('{host}',host))
KeyError: 'host'

**Comment by knassar702** [comment]
hello @hellofresh01 
please use [Bug Template](https://github.com/knassar702/scant3r/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D+YOUR_TITLE) and include more information's (your command , OS , python version etc ..)

**Comment by knassar702** [comment]
Hi @hellofresh01 
This Bug Has been Fixed 31075834dd75c81acaf69fee63128fd3e8a4caff
But please use [Bug Template](https://github.com/knassar702/scant3r/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D+YOUR_TITLE) for this issues

best regards
@knassar702
