### ISSUE TITLE
[BUG] utf-8 error

### ISSUE THREAD

**Issue by anasbousselham** [knassar702/scant3r#26]
Hi,
I have this error with every modules:
`File "/root/Tools/scant3r/modules/injheaders/__init__.py", line 38, in start
    if payload in r.content.decode('utf-8'):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf5 in position 18: invalid start byte
`

**Comment by knassar702** [comment]
hello @anasbousselham , thanks for this report 
>  I have this error with every modules

this problem from the encoding of response from your target , i change the decoding process from `utf-8` to `cp1252` and it's work  
try the last commit and tell me if this bug solved or not 
`$ git pull # for update to last commit`

best regards
@knassar702

**Comment by knassar702** [comment]
@anasbousselham  , Fixed for all modules , just download scant3r or run `$ git pull` command 

thanks

**Comment by anasbousselham** [comment]
Great thanks
