### ISSUE TITLE
Tool Not Working 

### ISSUE THREAD

**Issue by halfNeon** [knassar702/scant3r#43]
![Capture](https://user-images.githubusercontent.com/92912029/140726304-f597c891-e752-4cfa-98eb-fab5383b099a.PNG)
![Capture1](https://user-images.githubusercontent.com/92912029/140726848-afcaf0a4-b915-4bf8-be13-3c600a9f4125.PNG)
![Capture2](https://user-images.githubusercontent.com/92912029/140727094-9877b219-eacc-47a6-8894-f5f251448b24.PNG)
l 
Tool is not working

**Comment by halfNeon** [comment]
Please give the writeup for this tool.

**Comment by knassar702** [comment]
hi @halfNeon  , thanks for this report , I'll write a small writeup about my tools soon


Steps: 
* copy your host from https://app.interactsh.com/#/
* run these commads
```
$ git clone https://github.com/knassar702/scant3r ; cd scant3r
$ pip install -r requirements.txt
$ echo 'http://testphp.vulnweb.com/showimage.php | ./scant3r.py -m lorsrf -x 'http://%PARAM%.YOUR_HOST/%PATH%' -M GET
```

Video: https://www.linkedin.com/feed/update/urn:li:activity:6861114743919284224/

**Comment by knassar702** [comment]
hey @halfNeon , here is the writeup : https://knassar702.github.io/scant3r-ssrf

regards
@knassar702

**Comment by halfNeon** [comment]
thanks.
