### ISSUE TITLE
No option to set a Target URL.

### ISSUE THREAD

**Issue by domingosol** [knassar702/scant3r#44]
The arguments of the tool are missing the option to set the target url to scan.

The arguments are shown below:
[-h] [-H HEADERS] [-C COOKIES] [-v LOG_MODE] [-s DELAY] [-M METHODS] [-m MODULES] [-O] [-P LORSRF_PARAMETERS] 
[-l TARGETLIST] [-g] [-j] [-p PROXY] [-r] [-b BLINDXSS] [-x HOST] [-R] [-w THREADS] [-t TIMEOUT]

Is it missing, or something changed to the tool? As I can see from other [guides](https://www.youtube.com/watch?v=vFhsqjKz2F8&ab_channel=Briskinfosec)  url was an argument normally.

**Comment by knassar702** [comment]
you can set the target from pipe or text file

```bash
$ echo "http://testphp.vulnweb.com/" | ./scant3r.py 

$ cat targets.txt
http://testphp.vulnweb.com/

$ ./scant3r.py -l targets.txt
```

please read https://github.com/knassar702/scant3r/wiki/Usage
