### ISSUE TITLE
The script tldextract is installed in '/home/anoint/.local/bin' which is not on PATH.

### ISSUE THREAD

**Issue by whoami-anoint** [knassar702/scant3r#65]
WARNING: The script tldextract is installed in '/home/anoint/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script scant3r is installed in '/home/anoint/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by knassar702** [comment]
hey @whoami-anoint , you need to add .local/bin to your PATH env variable first 
```bash
$ export PATH=$PATH:~/.local/bin/
```

**Comment by whoami-anoint** [comment]
Okaay, let me try.
