### ISSUE TITLE
There's a problem exporting the SCANT3R.PY script 

### ISSUE THREAD

**Issue by KMx404** [knassar702/scant3r#9]
while developing a bash script I used some commands in order to launch scant3r.py, what i have noticed is that it only works while the existed launch run from the home directory. otherwise it displays errors such as: 
```

File "scant3r/scant3r.py", line 11, in <module>                                                                                    
    from libs import NewRequest as nq                                                                                                
  File "/home/mohamed/Desktop/projects/Hack4Squad/scant3r/libs/__init__.py", line 3, in <module>                                     
    from .requester import NewRequest      

```
Even though it works in the home directory and all the requirements are satisfied, nevertheless it still show me those errors. 

I worked on another python file just to be a middle man in order to be compatible between my bash script and scant3r.

**This is a sample of the normal scan in scant3r**
```
import sys, subprocess 

link = input("Your Target:$  ") 
subprocess.call("echo"+link+" | python3 scant3r/scant3r.py", shell=True) 
 
```
this is an alternate solution, I just didn't fully understand the issue here. Can you explain please

**Comment by knassar702** [comment]
hi @KMx404 
what is the version of python.?

im using python3.8
There are no errors here
![Screenshot at 2020-09-10 16-05-39](https://user-images.githubusercontent.com/45688522/92742053-c5e08800-f36e-11ea-8fb9-c52448dad3cf.png)

**Comment by KMx404** [comment]
the one in the Screenshot is the applicable solution that I just mentioned Bro. 
It shows errors about non-existing packages even though the requirements are satisfied

**Comment by knassar702** [comment]
hi @KMx404 
give me full error/command please
